name: HandleStaleDiscussions
on:
  schedule:
    - cron: '0 */4 * * *'
  discussion_comment:
    types: [created]

jobs:
  handle-stale-discussions:
    name: Handle stale discussions
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    steps:
      - name: Stale discussions action
        uses: meta-introspector/handle-stale-discussions@v1
        env:
          GITHUB_TOKEN:  ${{secrets.GITHUB_TOKEN}}
